### ISSUE TITLE
initAutoTracking not setting user cookie

### ISSUE THREAD

**Issue by mjmeintjes** [keen/keen-tracking.js#122] opened 2018-05-16 13:15 UTC
**What did I do?**
I include the code from the Readme in my page to enable autotracking.

**What happens?**
Each pageview creates a new user unique id. `keen` cookie is set to `{}`.

**What do I expect to happen?**
Cookie should be set once for each user, same unique id should be used for same user.

**What I think is happening**
Looking at the code for [cookie.prototype.set](https://github.com/keen/keen-tracking.js/blob/34e1e63cd45043250a123f9c9e87c3800989e9b1/lib/utils/cookie.js#L36), it doesn't seem to be handling the case where 3 arguments are passed in correctly.

**Comment by adamkasprowicz** [comment] 2018-05-16 16:30
Thank you for reporting! I'm fixing it right now and patched version of the keen-tracking lib will be published asap (max few hours)

**Comment by adamkasprowicz** [comment] 2018-05-16 20:36
The issue is fixed in keen-tracking@1.4.2
@mjmeintjes Thank you very much!

**Closed by adamkasprowicz** 2018-05-16 20:36 UTC
